kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: demo-sts-sc
provisioner: kubernetes.io/vsphere-volume
# Assumption is that vSAN is providing the storage and the storage policy called gold already exists
parameters:
    storagePolicyName: raid-1
    datastore: vsanDatastore
